baseURL = "https://hyvi.github.io" # <head> 里面的 baseurl 信息，填你的博客地址
title = "Elon`s Blog" # 浏览器的标题
languageCode = "zh-cn" # 语言
hasCJKLanguage = true # 开启可以让「字数统计」统计汉字
theme = "mogege" # 主题 (需要自己下载)

paginate = 11 # 每页的文章数
enableEmoji = true # 支持 Emoji
enableRobotsTXT = true # 支持 robots.txt


preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[frontmatter]
date = [":filename", ":default"]

[permalinks]
posts = "/:year/:month/:day/:slug"

[menu]

  [[menu.main]]
    name = "Pics"
    url = "/pics/"
    weight = 1

  [[menu.main]]
    name = "Tools"
    url = "/tools/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5

[params]
    since = 2017
    author = "Elon"                          # Author's name
    avatar = "https://img3.doubanio.com/icon/ul38294964-4.jpg"           # Author's avatar
    subtitle = "Just for Fun"                  # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other
    enableGitalk = true # gitalk 评论系统

    google_verification = ""

    description = "Elon 的个人博客" # (Meta) 描述
    keywords = "blog, Hugo, GNU/Linux, Linux, Ubuntu, Vim" # site keywords

    beian = ""
    baiduAnalytics = ""
    googleAnalytics = "" # Google 统计 id

    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

comment = true            # 是否开启评论
toc = true                # 是否开启目录
autoCollapseToc = true   # Auto expand and collapse toc

# Gitalk 评论配置（gitalk 请参考：https://github.com/gitalk/gitalk）
[params.gitalk] 
    owner = "Hyvi"              # Your GitHub ID
    admin = "Hyvi"      # GitHub repository owner and collaborators
    repo = "hyvi.github.com"               # The repo to store comments
    clientId = "e6d4916f9776f64681b8"           # Your client ID
    clientSecret = "0ecf1c39895b1e857f19b2f74b7e58982314c6da"       # Your client secret
    countSign = "条评论"
    id= "location.pathname" # The unique id of the page.
    labels= "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage= 15 # Pagination size, with maximum 100.
    pagerDirection= "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually= true # If it is 'false', it is auto to make a Github issue when the administrators login.
    distractionFreeMode= false # Enable hot key (cmd|ctrl + enter) submit comment.
